### ISSUE TITLE
Lỗi trắng trang.

### ISSUE THREAD

**Issue by motcaiten** [hongoctrien/nvform#6]
Chào anh.

Sau khi cài đặt module . E test thấy có lỗi này.

Khi điền đầy đủ thông tin vào form và gửi hoàn tất thì nó ra trang trắng . Anh xem fix lại dùm.

Em đang dùng bản nkv 4.0.9

**Comment by hongoctrien** [comment]
[Fixed](https://github.com/hongoctrien/nvform/commit/a449e591b48ac47e8fb22bda9f869edf1f79cdc4)
